name: Bank Bazasini Yangilash

# Qachon ishga tushishi kerak?
on:
  schedule:
    - cron: '0 0 * * *' # Har kuni kechasi soat 00:00 da avtomat ishlaydi
  workflow_dispatch: # GitHub sahifasidan qo'lda tugma bosib ishlatish uchun

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Repozitoriyani yuklash
        uses: actions/checkout@v3

      - name: Python muhitini tayyorlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Kerakli dasturlarni o'rnatish
        run: pip install requests beautifulsoup4

      - name: Skriptni ishga tushirish
        run: python update_banks.py

      - name: Natijani GitHub'ga saqlash (Commit)
        run: |
          git config --global user.name "Avtomat Bot"
          git config --global user.email "bot@1money.uz"
          git add banks.json
          # Agar o'zgarish bo'lmasa, xato bermasligi uchun "|| exit 0" qo'shilgan
          git commit -m "Bank foizlari saytlardan avtomat yangilandi 🔄" || exit 0
          git push
